version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: taskfranca_postgres
    environment:
      POSTGRES_DB: taskfranca
      POSTGRES_USER: taskfranca
      POSTGRES_PASSWORD: Famoso3capa
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
